services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  pedido-ms:
    build: ./pedido-ms
    volumes:
      - ./pedido-ms/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NATS_SERVERS: nats://nats-server:4222
      PORT: 3000
      DATABASE_URL: file:./dev.db

  inventario-ms:
    build: ./inventario-ms
    volumes:
      - ./inventario-ms/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - "3001:3001"
    environment:
      NATS_SERVERS: nats://nats-server:4222
      PORT: 3001
      DATABASE_URL: file:./dev.db

  pago-ms:
    build: ./pago-ms
    volumes:
      - ./pago-ms/src:/usr/src/app/src
    command: npm run start:dev
    ports:
      - "3002:3002"
    environment:
      NATS_SERVERS: nats://nats-server:4222
      PORT: 3002
      DATABASE_URL: file:./dev.db
